on: push

name: Compile data

jobs:
  render:
    name: Compile data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install Dependencies
        run: |
            install.packages(c("remotes", "rjson", "jsonlite"))
            remotes::install_deps(dependencies = TRUE)
            remotes::install_github(c("tidyverse/dplyr", "easystats/see", "easystats/effectsize"))
        shell: Rscript {0}
      - name: Restore packages
        run: |
            if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
            renv::restore()
        shell: Rscript {0}
      - name: Run script
        run: |
            source("analysis/make_data.R")
        shell: Rscript {0}
      - name: Commit results
        run: |
          git commit analysis/data.csv -m 'Make data.csv' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
